services:
  1panel:
    image: koryking/1panel:latest
    container_name: 1panel
    ports:
      - 26000:10086
    volumes:
      - /share/CACHEDEV1_DATA/Public/Docker/1panel:/opt/1panel
      - /share/CACHEDEV1_DATA/Public/:/share/CACHEDEV1_DATA/Public/
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Asia/Shanghai
      - PANEL_BASE_DIR=/opt/1panel
      - PANEL_PORT=10086
      - PANEL_ENTRANCE=123456
      - PANEL_USERNAME=admin
      - PANEL_PASSWORD=password
    network_mode: bridge
    restart: always
