services:
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    ports:
      - 30030:9117
    volumes:
      - /share/CACHEDEV1_DATA/Public/Docker/jackett/config:/config
      - /share/CACHEDEV1_DATA/Public/Docker/jackett/downloads:/downloads
    environment:
      - PUID=1001
      - PGID=100
      - TZ=Asia/Shanghai
      - AUTO_UPDATE=false
    restart: always
    network_mode: bridge
