services:
  emulatorjs:
    image: lscr.io/linuxserver/emulatorjs:latest
    container_name: emulatorjs
    ports:
      - 23000:3000
      - 23001:80
    volumes:
      - /volume1/My/Docker/emulatorjs/config:/config
      - /volume1/My/Docker/emulatorjs/data:/data
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
