services:
  iyuuplus:
    image: iyuucn/iyuuplus:latest
    container_name: iyuuplus
    ports:
      - 30000:8780
    volumes:
      - /volume1/My/Docker/iyuuplus/iyuu:/iyuu
      - /volume1/My/Docker/iyuuplus/data:/data
      - /volume1/My/Docker/qbittorrent/qBittorrent/BT_backup:/qb
      - /volume1/My/Docker/transmission/torrents:/tr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
