services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    ports:
      - 21000:4533
    volumes:
      - /volume1/My/Docker/navidrome:/data
      - /volume1/My/Music:/music
    restart: always
    network_mode: bridge
