services:
  wechat:
    image: ricwang/docker-wechat:latest
    container_name: wechat
    privileged: true
    ports:
      - 26005:5800
      - 26006:5900
    volumes:
      - /volume1/My/Docker/wechat/config:/root/.xwechat
      - /volume1/My/Docker/wechat/files:/root/xwechat_files
      - /volume1/My/Downloads:/root/downloads
    environment:
      - TZ=Asia/Shanghai
      - LANG=zh_CN.UTF-8
      - USER_ID=0
      - GROUP_ID=0
      - WEB_AUDIO=0
    network_mode: bridge
    restart: always
