services:
  cloudsaver:
    image: jiangrui1994/cloudsaver:latest
    container_name: cloudsaver
    ports:
      - 24010:8008
    volumes:
      - /volume1/@home/Testroot/Docker/cloudsaver/data:/app/data
      - /volume1/@home/Testroot/Docker/cloudsaver/config:/app/config
    restart: always
    network_mode: bridge
