services:
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    ports:
      - 30030:9117
    volumes:
      - /volume1/@home/Testroot/Docker/jackett/config:/config
      - /volume1/@home/Testroot/Docker/jackett/downloads:/downloads
    environment:
      - PUID=1001
      - PGID=10
      - TZ=Asia/Shanghai
      - AUTO_UPDATE=false
    restart: always
    network_mode: bridge
