services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    ports:
      - 26030:8080
    volumes:
      - /volume1/@home/Testroot/Docker/open-webui:/app/backend/data
    environment:
      - ENABLE_OPENAI_API=False
      - OFFLINE_MODE=True
      - OLLAMA_BASE_URL=http://127.0.0.1:26025
      - USE_OLLAMA_DOCKER=False
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
