services:
  alist-strm:
    image: itefuir/alist-strm:latest
    container_name: alist-strm
    stdin_open: true
    tty: true
    ports:
      - 20330:5000
    volumes:
      - /var/lib/casaos_data/.media/SSD-Storage/Docker/alist-strm:/config
      - /var/lib/casaos_data/.media/SSD-Storage/Video:/Video
    restart: always
    network_mode: bridge
