services:
  godoos:
    image: godoos/godoos:latest
    container_name: godoos
    ports:
      - 26045:56780
    volumes:
      - /var/lib/casaos_data/.media/SSD-Storage/Docker/godoos:/root/.godoos/os
    environment:
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
