services:
  v2raya:
    image: v2raya/v2raya:latest
    container_name: v2raya
    privileged: true
    ports:
      - 27010:2017
    volumes:
      - /var/lib/casaos_data/.media/SSD-Storage/Docker/v2raya:/etc/v2raya
    restart: always
    network_mode: bridge
