services:
  1panel:
    image: koryking/1panel:latest
    container_name: 1panel
    ports:
      - 26000:10086
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Docker/1panel:/opt/1panel
      - /tmp/zfsv3/sata11/13051661743/data/:/tmp/zfsv3/sata11/13051661743/data/
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Asia/Shanghai
      - PANEL_BASE_DIR=/opt/1panel
      - PANEL_PORT=10086
      - PANEL_ENTRANCE=123456
      - PANEL_USERNAME=admin
      - PANEL_PASSWORD=password
    network_mode: bridge
    restart: always
