name: chasbook

networks:
  cashbook:
    external: true

services:
  postgres:
    image: postgres:14
    container_name: postgres-cashbook
    ports:
      - "29005:5432"
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cashbook
    restart: always
    networks:
      - cashbook
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d cashbook"]
      interval: 5s
      retries: 5
      start_period: 30s

  cashbook:
    container_name: cashbook
    image: dingdangdog/cashbook:latest
    ports:
      - "25000:9090"
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Docker/cashbook/data:/app/data
    environment:
      - DATABASE_URL=postgresql://admin:password@postgres-cashbook:5432/cashbook?schema=public
      - NUXT_DATA_PATH=/app/data
      - NUXT_APP_URL=https://127.0.0.1:29005
      - NUXT_AUTH_ORIGIN=https://127.0.0.1:29005/api/auth
      - NUXT_AUTH_SECRET=auth_secret
      - NUXT_ADMIN_USERNAME=admin
      - NUXT_ADMIN_PASSWORD=749f09bade8aca755660eeb17792da880218d4fbdc4e25fbec279d7fe9f65d70
    restart: always
    networks:
      - cashbook
    depends_on:
      postgres:
        condition: service_healthy
