services:
  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest
    container_name: chinesesubfinder
    ports:
      - 20025:19035
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Docker/chinesesubfinder/config:/config
      - /tmp/zfsv3/sata11/13051661743/data/Docker/chinesesubfinder/cache:/app/cache
      - /tmp/zfsv3/sata11/13051661743/data/Video:/media
    environment:
      - PUID=1016
      - PGID=1017
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
