services:
  emby:
    image: amilys/embyserver:latest
    container_name: embyserver
    privileged: true
    ports:
      - 20015:8096
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Docker/emby/config:/config
      - /tmp/zfsv3/sata11/13051661743/data/Video:/data
    restart: always
    network_mode: bridge
