services:
  godoos:
    image: godoos/godoos:latest
    container_name: godoos
    ports:
      - 26045:56780
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Docker/godoos:/root/.godoos/os
    environment:
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
