services:
  hanime-server:
    image: heisenyu/hanime-server:latest
    container_name: hanime-server
    ports:
      - 20055:7788
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Docker/hanime-server:/app/backend/db
      - /tmp/zfsv3/sata11/13051661743/data/Downloads:/app/backend/downloads
    environment:
      - USE_PROXY=true
      - PROXY_URL=http://127.0.0.1:80
    restart: always
    network_mode: bridge
