services:
  jellyfin:
    image: nyanmisaka/jellyfin:latest
    container_name: jellyfin
    privileged: true
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 20010:8096
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Docker/jellyfin/config:/config
      - /tmp/zfsv3/sata11/13051661743/data/Docker/jellyfin/cache:/cache
      - /tmp/zfsv3/sata11/13051661743/data/Video:/video
    restart: always
    network_mode: bridge
