services:
  moviepilot:
    image: jxxghp/moviepilot-v2:latest
    container_name: moviepilot
    ports:
      - 20005:3000
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Video:/downloads
      - /tmp/zfsv3/sata11/13051661743/data/Docker/moviepilot:/config
    environment:
      - NGINX_PORT=3000
      - PORT=3001
      - PUID=1016
      - PGID=1017
      - UMASK=022
      - TZ=Asia/Shanghai
      - SUPERUSER=admin
    restart: always
    network_mode: bridge
