services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    ports:
      - 21000:4533
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Docker/navidrome:/data
      - /tmp/zfsv3/sata11/13051661743/data/Music:/music
    restart: always
    network_mode: bridge
