services:
  reader:
    image: hectorqin/reader:latest
    container_name: reader
    ports:
      - 22005:8080
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Docker/reader/log:/log
      - /tmp/zfsv3/sata11/13051661743/data/Docker/reader/storage:/storage
    restart: always
    network_mode: bridge
