services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: pdftool
    ports:
      - 26015:8080
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Docker/pdftool/trainingData:/usr/share/tessdata
      - /tmp/zfsv3/sata11/13051661743/data/Docker/pdftool/extraConfigs:/configs
      - /tmp/zfsv3/sata11/13051661743/data/Docker/pdftool/customFiles:/customFiles/
      - /tmp/zfsv3/sata11/13051661743/data/Docker/pdftool/logs:/logs/
      - /tmp/zfsv3/sata11/13051661743/data/Docker/pdftool/pipeline:/pipeline/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - LANGS=en_GB
    restart: always
    network_mode: bridge
