services:
  sun-panel:
    image: hslr/sun-panel:latest
    container_name: sun-panel
    ports:
      - 30005:3002
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Docker/sun-panel:/app/conf
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    network_mode: bridge
