services:
  verysync:
    image: jonnyan404/verysync:latest
    container_name: verysync
    ports:
      - 26010:8886
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Synchronous:/data
    restart: always
    network_mode: bridge
