name: ezbookkeeping

networks:
  ezbookkeeping:
    external: true

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-ezbookkeeping
    ports:
      - "29000:3306"
    volumes:
      - /mnt/test/Docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ezbookkeeping
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    restart: always
    networks:
      - ezbookkeeping
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -ppassword"]
      interval: 5s
      retries: 10
      start_period: 30s

  ezbookkeeping:
    image: mayswind/ezbookkeeping:latest
    container_name: ezbookkeeping
    ports:
      - "25005:8080"
    volumes:
      - /mnt/test/Docker/ezbookkeeping/storage:/ezbookkeeping/storage
      - /mnt/test/Docker/ezbookkeeping/log:/ezbookkeeping/log
      - /etc/localtime:/etc/localtime:ro
    environment:
      - EBK_SERVER_ENABLE_GZIP=true
      - EBK_DATABASE_TYPE=mysql
      - EBK_DATABASE_HOST=mysql-ezbookkeeping:3306
      - EBK_DATABASE_NAME=ezbookkeeping
      - EBK_DATABASE_USER=root
      - EBK_DATABASE_PASSWD=password
      - EBK_LOG_MODE=console file
      - EBK_SECURITY_SECRET_KEY=123456
    restart: always
    networks:
      - ezbookkeeping
    depends_on:
      mysql:
        condition: service_healthy
    
