services:
  openlist:
    image: openlistteam/openlist:v4.0.4-aio
    container_name: openlist
    ports:
      - 24005:5244
    volumes:
      - /mnt/test/Docker/openlist:/opt/alist/data
    environment:
      - PUID=1000
      - PGID=1001
      - UMASK=022
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
