services:
  homeassistant:
    image: homeassistant/home-assistant:latest
    container_name: homeassistant
    ports:
      - 25030:8123
    volumes:
      - /mnt/dm-1/.ugreen_nas/509155/Docker/homeassistant:/config
    environment:
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
