services:
  moontv:
    image: ghcr.io/senshinya/moontv:latest
    container_name: moontv
    ports:
      - 20050:3000
    # volumes:
    #   - /mnt/dm-1/.ugreen_nas/509155/Docker/moontv/config.json:/app/config.json
    environment:
      - PASSWORD=password
    restart: always
    network_mode: bridge
