services:
  synctv:
    image: synctvorg/synctv:latest
    container_name: synctv
    ports:
      - 20040:8080
    volumes:
      - /mnt/dm-1/.ugreen_nas/509155/Docker/synctv:/root/.synctv
    restart: always
    network_mode: bridge
