services:
  dockge:
    image: louislam/dockge:1
    container_name: dockge
    ports:
      - 26005:5001
    volumes:
      - /vol1/1000/Docker/dockge/data:/app/data
      - /vol1/1000/Docker/dockge:/home/stacks
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    network_mode: bridge
