services:
  frpc:
    image: snowdreamtech/frpc:latest
    container_name: frpc
    volumes:
      - /vol1/1000/Frpc:/etc/frp
    command: -c /etc/frp/frpc.ini
    restart: always
    network_mode: host
