services:
  homebox:
    image: hfhc1309/homebox-zh:latest
    container_name: homebox
    ports:
      - 22115:7745
    volumes:
      - /vol1/1000/Docker/homebox:/data/
    environment:
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
