services:
  iptv-api:
    image: guovern/iptv-api:latest
    container_name: iptv-api
    ports:
      - 20300:8000
    volumes:
      - /vol1/1000/Docker/iptv-api/config:/iptv-api/config
      - /vol1/1000/Docker/iptv-api/output:/iptv-api/output
    restart: always
    network_mode: bridge
