services:
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    ports:
      - 25110:9117
    volumes:
      - /vol1/1000/Docker/jackett/config:/config
      - /vol1/1000/Docker/jackett/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Asia/Shanghai
      - AUTO_UPDATE=false
    restart: always
    network_mode: bridge
