services:
  lyricapi:
    image: hisatri/lyricapi:latest
    container_name: lyricapi
    ports:
      - 20410:28883
    volumes:
      - /vol1/1000/Music:/music
    restart: always
    network_mode: bridge
