services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 28000:3306
    volumes:
      - /vol1/1000/Docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    restart: always
    network_mode: bridge
