services:
  qiandao:
    image: qdtoday/qd:latest
    container_name: qiandao
    ports:
      - 26105:80
    volumes:
      - /vol1/1000/Docker/qiandao/:/usr/src/app/config
    restart: always
    network_mode: bridge
