services:
  synctv:
    image: synctvorg/synctv:latest
    container_name: synctv
    ports:
      - 20205:8080
    volumes:
      - /vol1/1000/Docker/synctv:/root/.synctv
    restart: always
    network_mode: bridge
