services:
  transmission:
    image: linuxserver/transmission:4.0.5
    container_name: transmission
    ports:
      - 25005:9091
    volumes:
      - /vol1/1000/Docker/transmission:/config
      - /vol1/1000/Video:/downloads
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Asia/Shanghai
      - TRANSMISSION_WEB_HOME=/config/webui/Transmission Theme
      - USER=root
      - PASS=root
    restart: always
    network_mode: bridge
