services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    ports:
      - 24110:80
    volumes:
      - /vol1/1000/Docker/vaultwarden:/data
    environment:
      - DOMAIN=https://vaultwarden.example.com
      - SIGNUPS_ALLOWED=true
    restart: always
    network_mode: bridge
