services:
  verysync:
    image: jonnyan404/verysync:latest
    container_name: verysync
    ports:
      - 21105:8886
    volumes:
      - /vol1/1000/Synchronous:/data
    restart: always
    network_mode: bridge
