services:
  wallos:
    image: bellamy/wallos:latest
    container_name: wallos
    ports:
      - 22110:80
    volumes:
      - /vol1/1000/Docker/wallos/data:/var/www/html/db
      - /vol1/1000/Docker/wallos/logos:/var/www/html/images/uploads/logos
    environment:
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
