services:
  xiaoaimusic:
    image: hanxi/xiaomusic:latest
    container_name: xiaoaimusic
    ports:
      - 20425:8090
    volumes:
      - /vol1/1000/Docker/xiaoaimusic:/app/conf
      - /vol1/1000/Music:/app/music
    environment:
      - XIAOMUSIC_PUBLIC_PORT=8090
    restart: always
    network_mode: bridge
